# ansible/deploy_chatbot.yml
- hosts: localhost
  connection: local # Assuming Ansible is run from the same machine where K3d and kubeconfig is set up
  gather_facts: no

  vars:
    k8s_manifest_path: "../kubernetes"
    k3d_cluster_name: "chatbot-k3s-cluster"

  tasks:
    - name: "Check if K3d cluster '{{ k3d_cluster_name }}' is running"
      ansible.builtin.command:
        cmd: "k3d cluster get {{ k3d_cluster_name }}"
      register: k3d_cluster_status
      changed_when: false
      failed_when: k3d_cluster_status.rc != 0
      tags: [preflight, k3d_check]

    - name: Apply PersistentVolume and PersistentVolumeClaim
      kubernetes.core.k8s:
        state: present
        src: "{{ k8s_manifest_path }}/pv-pvc-k3d.yaml"

    - name: Apply Chatbot Deployment
      kubernetes.core.k8s:
        state: present
        src: "{{ k8s_manifest_path }}/deployment-k3d.yaml"
